### ISSUE TITLE
Make constants configurable

### ISSUE THREAD

**Issue by quackduck** [quackduck/devzat#102]
It would be nice to have the following definable in a YAML config file.
- [x] The admin list
- [x] Data directory (stores bans and logs inside)
- [x] SSH host key location
- [x] Credentials file
- [x] SSH listen port (should also be definable as an env var)
- [x] Profiling port (or maybe profiling should just be removed)

The following could be merged into a single credentials file:
- [x] Slack API key
- [x] Slack channel ID
- [x] Twitter credentials

**Comment by sector-f** [comment]
If you wanted to get really fancy, you could use cobra + viper
Then you would have:

- A really nice CLI interface
- A configuration file (Viper can handle reading config files for you)
- The ability to override values in the configuration file using CLI flags
- The ability override both the configuration file and CLI flags using environment variables

**Comment by quackduck** [comment]
Commit https://github.com/quackduck/devzat/commit/382708a736196264ca96518c0adb69b21c3e5c73 concludes this change.
