### ISSUE TITLE
Prompt changes

### ISSUE THREAD

**Issue by quackduck** [quackduck/devzat#103]
Include DM status so that it isn't confusing whether a message will be a DM or go to a room.

Possible formats:

```
ishan: previous message
[to arc] ishan: wheee input
```
```
ishan: previous message
[arc] ishan: wheee input
```
Maybe this should show the current room in non-main rooms
```
ishan: previous message
[to #chaos] ishan: wheee input
```
```
ishan: previous message
[#chaos] ishan: wheee input
```

Maybe a more shell-y prompt like this:
```
ishan: previous message
ishan ~/#chaos $ wheee input
```

A major issue with these is that sent messages have a prefix shorter than and different to the prompt. As of now, the format is:
```
ishan: previous message
ishan: whee input
```

The current format has messages that look very similar to how they did on the prompt. However, people do have to use the `pwd` or `cd` commands to figure out their room/DM status as of now.

**Comment by Arkaeriit** [comment]
I feel like the shell-y prompt really fits in Devzat's style.
