### ISSUE TITLE
readBans/saveBans functions may leave file handle open

### ISSUE THREAD

**Issue by sector-f** [quackduck/devzat#104]
The code in question is this, from the `util.go` file:

```go
func saveBans() {
	f, err := os.Create("bans.json")
	if err != nil {
		l.Println(err)
		return
	}
	j := json.NewEncoder(f)
	j.SetIndent("", "   ")
	err = j.Encode(bans)
	if err != nil {
		rooms["#main"].broadcast(devbot, "error saving bans: "+err.Error())
		l.Println(err)
		return
	}
	f.Close()
}

func readBans() {
	f, err := os.Open("bans.json")
	if err != nil && !os.IsNotExist(err) { // if there is an error and it is not a "file does not exist" error
		l.Println(err)
		return
	}
	err = json.NewDecoder(f).Decode(&bans)
	if err != nil {
		rooms["#main"].broadcast(devbot, "error reading bans: "+err.Error())
		l.Println(err)
		return
	}
	f.Close()
}
```
These should probably have a `defer f.Close()` call after the file is opened successfully. Currently, the file handle never gets closed if the file exists and Encode/Decode fails.

**Comment by quackduck** [comment]
I’m surprised me or a linter hasn’t found this yet, will be fixed in the next commit 👍

thanks

**Comment by sector-f** [comment]
Not a problem!

Also, I do wonder about `readBans()`: shouldn't the function return early if the file does not exist? I'm pretty sure `f` won't be valid in that case anyways. Or is this behavior intentional so that a "file does not exist" broadcast message gets generated?

**Comment by quackduck** [comment]
I forgot to update this issue. Was fixed by https://github.com/quackduck/devzat/commit/bf1a56fb87ca0918c17ce95d6495347375b1f81f
