### ISSUE TITLE
error in go build

### ISSUE THREAD

**Issue by David-Valters** [quackduck/devzat#106]
build devchat: cannot load embed: malformed module path "embed": missing dot in first path element
![зображення](https://user-images.githubusercontent.com/46930139/161426216-3ffb97aa-537e-4994-a83b-8bdf09e98c31.png)
 OS: Ubuntu 20.04.4 LTS on Windows 10 x86_64
go version go1.13.8 linux/amd64

**Comment by Arkaeriit** [comment]
This is probably due to the fact that you use an older Go version. Devzat is meant to be build with go 1.17.

**Comment by David-Valters** [comment]
> Можливо, це пов’язано з тим, що ви використовуєте старішу версію Go. Devzat планується зібрати з go 1.17.

yes you were right
go version go1.17 linux/amd64
