### ISSUE TITLE
API Design

### ISSUE THREAD

**Issue by quackduck** [quackduck/devzat#107]
Devzat should have an API for people to write their own bots & plugins.

The API should have some sort of authentication built in so server managers can ensure privacy and control what bots and plugins run on their instance. This is clearly needed in case we decide the API should provide a way to edit user messages (this would let custom emojis become such a plugin instead of a core feature, for example)

One way this could be done is to have authenticated JSON + HTTP endpoints for receiving or sending messages.

@Merlin04 & @CodeLongAndProsper90 have ideas I really like. Plugins can be programs that only run on the server (so plugins would need to be allowed by the server manager) and communicate with the Devzat instance in some way.

**Comment by CodeLongAndProsper90** [comment]
I think that having plugins be spawned as children and passing messages across the child's stdin/stdout is the simplest way to do it.

**Comment by Merlin04** [comment]
For reference here's the API design idea I came up with on the slack. It's missing some important things but it covers most of the core features (like events and middleware):


Actions
```
 register_cmd(name: string)
 send_message(from?: string, ephemeral?: bool)
 send_image(src_type: "file" | "url" | "b64", src: string)
 register_listener(event: "send" | "something else?", middleware?: bool, once?: bool)
 mw_edit_message(text?: string)
 mw_done()
```

Messages
```
 event(name: string, data?: object)
 cmd(name: string, args: string)
```

The actual data format would look something like
```
 {
     type: string,
     args: object
 }
```

**Comment by quackduck** [comment]
IIRC you wanted this to use gRPC, right?

**Comment by Merlin04** [comment]
It also might be a good idea to consider versioning the API, so plugins can detect breaking changes

**Comment by Merlin04** [comment]
@quackduck I've heard gRPC is good for efficient inter-process communication but I have no idea how practical it is/how easy it is to integrate with plugins

**Comment by quackduck** [comment]
🎉 current solution: https://github.com/quackduck/devzat/commit/302551281ffabb4e6154bd2101b22bdb457b2002

(Thanks Benjamin!)
