### ISSUE TITLE
wondering why color formatter saves the bans file

### ISSUE THREAD

**Issue by gravestench** [quackduck/devzat#111]
https://github.com/quackduck/devzat/blob/cca970dfebacfe36b67d2bb372a233e15aa1f6bd/colors.go#L136
![image](https://user-images.githubusercontent.com/936440/162356157-6949f464-91f4-4e58-af74-4e4dad2064e4.png)

**Comment by quackduck** [comment]
I have no idea; thanks for bringing this to my attention. Probably because I _think_ bans used to store the username.

**Comment by quackduck** [comment]
(Not solved yet)

**Comment by quackduck** [comment]
Also this isn’t the only (or main) usage of `saveBans` so it isn’t really that it’s responsible for saving bans.

**Comment by gravestench** [comment]
sure, but it is evidently responsible for the call here, we just don't know why.

**Comment by quackduck** [comment]
Probably a remnant of some small desire to keep everything synced which isn’t needed now
