### ISSUE TITLE
why does `pwd` print in someone else's shell?

### ISSUE THREAD

**Issue by gravestench** [quackduck/devzat#113]
https://github.com/quackduck/devzat/blob/73bbc47eb090fcfb5ca254d899d85eb81e76c6e8/commands.go#L721
![image](https://user-images.githubusercontent.com/936440/162536886-8c2f02a0-9c71-4bf2-b170-dbaf163678ba.png)

when user `A` issues command `pwd` while in a private chat with user `B`, both `A` and `B` will have shit printed in their shell. that's wild.

**Comment by quackduck** [comment]
I have no idea. Good spot!

Introduced in https://github.com/quackduck/devzat/pull/54/commits/903e5ba61d5dcd4470a7256c1c56d6440f7d9527

**Comment by quackduck** [comment]
SMH language tho
