### ISSUE TITLE
Keep connection alive

### ISSUE THREAD

**Issue by UBFI** [quackduck/devzat#124]
After a while if a users has been connected without saying anything their connection to the server will be closed.
Connection to <Private Devzat Server> closed by remote host.

**Comment by quackduck** [comment]
Are you sure the client doesn't have a timeout set? How long is a while? What is your SSH version?

**Comment by UBFI** [comment]
Tested stock MacOS OpenSSH_8.6p1, LibreSSL 3.3.5 and with Putty on Windows.

**Comment by quackduck** [comment]
How long does it take for it to kick you?

**Comment by quackduck** [comment]
I wonder if this might affect all network connections to your server. Does running `nc -l <port>` on the server, and then `nc <server hostname> <port>` stay open indefinitely?

**Comment by UBFI** [comment]
This issue was found to be directly caused by my tunneling provider however the issue can and should be mitigated in Devzat's codebase. Other SSH daemons function normally even being connected for several days even on the same tunnel and port.

**Comment by quackduck** [comment]
If `netcat` doesn't work fixing this problem would be more of an enhancement than a bug. We'd have to investigate how those other SSH daemons keep the connection open.

**Comment by UBFI** [comment]
I actually found that current versions of netcat do NOT close the connection but it simply hangs for about 20ms every 5-10 minutes.

**Comment by quackduck** [comment]
How did you find out there was a tunneling problem?

**Comment by quackduck** [comment]
Fixed in https://github.com/quackduck/devzat/commit/55419b6fb9063c822faca92aa93adbdb60ed18ab
