### ISSUE TITLE
got banned lol

### ISSUE THREAD

**Issue by joaofnds** [quackduck/devzat#136]
![image](https://user-images.githubusercontent.com/9938253/193432900-3cb36286-e2c3-404b-ac99-be8bc9af9cf9.png)

send too many messages at once from vim to the chat using tmux 🙃

id: dff3315bce50ebc4a2647bd3d79c327de77992fda848bd0f1a142ef1d30a4979

**Comment by quackduck** [comment]
LOL. here's what i sent shortly after (didn't realize devbot had kicked you already)
<img width="585" alt="image" src="https://user-images.githubusercontent.com/38882631/193433010-07ee308c-a527-4ac7-893b-42c1dcd10058.png">

**Comment by quackduck** [comment]
You're unbanned now. Feel free to log back in!
