### ISSUE TITLE
It freaks out on me when I use kitty terminal 

### ISSUE THREAD

**Issue by lostfile1** [quackduck/devzat#137]
I don't have any screenshots but when I try to log into the server using Kitty terminal it craps out a bunch of junk on the screen I don't have any screenshots right now. I'm at work but I will give you more details later

**Comment by quackduck** [comment]
Alright awaiting details

**Comment by Arkaeriit** [comment]
When I try to get to a self-host Devzat instance with Kitty, I don't have any issues.

**Comment by lostfile1** [comment]
> When I try to get to a self-host Devzat instance with Kitty, I don't have any issues.

maybe its just my build of kitty idk

**Comment by Arkaeriit** [comment]
I tried to log on the standard Devzat instance it went well as well. What is your kitty version and plugin lists? To see if I can recreate it.

**Comment by quackduck** [comment]
works fine on kitty for me too

**Comment by Arkaeriit** [comment]
With about two years of no answer from @lostfile1, we can probably close the issue.
