### ISSUE TITLE
Changing behavior of `cd`

### ISSUE THREAD

**Issue by Arkaeriit** [quackduck/devzat#156]
The behavior of `cd` is a bit weird. When being called with no argument, it list the content of all rooms. In an UNIX shell, `cd` with no arguments brings the user to their home directory.

To make Devzat feels more UNIXy, we could change `cd` so that calling it with no arguments is an alias to `cd #main` and we add a `-R` option to `ls` that list the content of all rooms.

What do you think about it?

**Comment by quackduck** [comment]
Hmm. I still want the output of `cd` (shows all rooms and each one's users) to be really easy to see (ls -R sounds a little painful to type). The current behavior is based on another UNIX-y commonality: a command often shows how it can be used when it's given no arguments. In this case, cd just shows all the rooms you could use it to get to. The real cd ofc replaces the normal no-arg behavior with the go-to-home behavior.

**Comment by Arkaeriit** [comment]
That's fair. No need to change anything then.
