### ISSUE TITLE
May we have different languages supported？

### ISSUE THREAD

**Issue by B17w153** [quackduck/devzat#163]
i tried to compile it with modified "cmds" output in chinese, but some how it outputs strangely with unreadable contexts when i send that，it seems that there was an encoding error or sth,is there any way to fix that?

**Comment by B17w153** [comment]
i do that because of it would be some difficulties for my friends to read english,and it would be great for them to understand how to use the devzat commands in chinese,could some one help?

**Comment by B17w153** [comment]
sorry pal,i have confirmed that it was my own fault.
i messed up with encoding option,which lead to what have happend.
but thanks anyway,appricate your project!
it is really coool!

**Comment by quackduck** [comment]
oh okay cool that you got it working :)
