### ISSUE TITLE
Use Docker Container to Run Devzat Servers

### ISSUE THREAD

**Issue by CaenJones** [quackduck/devzat#194]
For a quicker and potentially hands free install process, as well as adding isolation between devzat and the host system. Severs could be run inside a docker container. My first attempt at a dockerfile is [here](https://github.com/CaenJones/devzat). If you have anything to improve or modify, please create a PR

**Comment by quackduck** [comment]
I don't see a dockerfile there. Don't containers usually take up a lot of memory? I guess we could provide this as an option.

**Comment by peauc** [comment]
Hello, this issue is marked as completed but I don't see anything related to PR. Could we re-open it ?
