### ISSUE TITLE
Add timestamps

### ISSUE THREAD

**Issue by asrp** [quackduck/devzat#21]
Nice project! :+1: 

I'd be nice to have timestamps in the chat for messages and events, maybe optional ones that can be toggled.

Someone in the chat suggested I make an issue for this, but no rush or anything.

**Comment by quackduck** [comment]
I have tried this before, lemme try implementing again, I'll let you know how it goes.

**Comment by quackduck** [comment]
The problem with this is that we have no idea what the user's time zone is (we could try getting it with IPs but that'll be quite a hassle)
What we could do is instead display the timestamp as minutes since the user joined, would that be okay?

**Comment by quackduck** [comment]
Or we could ask the user to add in their timezone

**Comment by quackduck** [comment]
Implemented both!

**Comment by quackduck** [comment]
Lookin good: 
![image](https://user-images.githubusercontent.com/38882631/118932105-b3383d00-b958-11eb-9b89-aba3ba3bcfb6.png)

**Comment by quackduck** [comment]
should it show the seconds too or is that unnecessary?

**Comment by asrp** [comment]
Nice, that was really fast! User specified timezones looks pretty cool to me. I'd want to see seconds but I could see it working without that too.

So, in some IRC clients they have timestamps on the same line on the left. Something like

```
[1m in]    ishan: test
[4m in]    ishan: test 2
[4m in]    ishan: nice!
[4m in]    ishan: /tz Asia/Dubai
[10:44 am] ishan: test!
```

or maybe it could be distinguished from the rest in some other way

```
1m in
  ishan: test
4m in
  ishan: test 2
  ishan: nice!
  ishan: /tz Asia/Dubai
10:44 am
  ishan: test!
```

Indenting might mess up some of your other layout though, so don't know if it is worth it.

I'm happy to have timestamps though, even the way they are now.

**Comment by quackduck** [comment]
I like the second idea you have! But you're right about it messing up some layouts. Is there another way we could distinguish the stamps? Maybe I could have an extra line above and below the stamps or maybe I could change the timestamp's color, what do you think?

**Comment by quackduck** [comment]
(I think the first design (of the IRC clients) makes the stamps too intrusive and the interface less clean)

**Comment by asrp** [comment]
Yeah, I think color would work. I think an empty line above could work too. We'd need to try it to see if two lines for timestamps is too much, though I think an empty line is easier to visually distinguish than color.

**Comment by quackduck** [comment]
tried empty lines, looked bad, now we have timestamps that take up only one line, print on the right for zero intrusive-ness and also leave one line empty between messages! absolutely perfect!
