### ISSUE TITLE
Will not compile on Raspberry Pi

### ISSUE THREAD

**Issue by peterahunt** [quackduck/devzat#212]
With the following error...

gcc: error: unrecognized command-line option '-marm'

**Comment by quackduck** [comment]
What command did you run exactly? Provide the full output

**Comment by peterahunt** [comment]
I simply used  - 'go build' in the devzat directory.

I have setup several servers on ubuntu with no problems, and decided to put it on my Pi. Looking into the error, I have found a number of references to this not being a valid option on a Pi, as it does not have that option...

for example...
 
You get this error because there is no -marm option in gcc. There is an -march option ( arch -> 'architecture'

**Comment by quackduck** [comment]
Was that the only output it had? Try running `CGO_ENABLED=0 go build`

**Comment by peterahunt** [comment]
OK, thank you very much, use it all the time.

**Comment by quackduck** [comment]
Awesome! Are you into Go?

**Comment by peterahunt** [comment]
I am currently trying to learn it in a typically ass-backward fashion.  I was 'into' Basic on an Apple ][ when I was in school, if that gives you an idea of my age.  I have gained a little bit of info on various languages over the years, but never had time, etc.  Recently I noticed that go seems to be something I can get my head around.  Simple enough, powerful enough.  I only have interest in making things for me, hobby-like.  I am your typical before internet kind of guy, ran a BBS, installed ISDN connections, back before programming was taught is any schools at all.  So we all taught each other what we learned, copied code from magazines, etc.  

Now that I have time, seems there are a lot more resources out there.  So here I am. 

I guess that qualifies as into go!  I'll update you in a few months! ;)

**Comment by quackduck** [comment]
Crazy... I'm currently a freshman in college so this is absurd for me.

**Comment by peterahunt** [comment]
Man, I am not that old. lol. I came in with the Commodore 64s and Apple ][s...  But yeah, it has really really changed.

**Comment by peterahunt** [comment]
Honestly, we would hold the phone up to the recorder(or the modem) and you could save or input programs remotely.  It was bleeding edge, absurdly bleeding edge.  And now, it is absurd to think we did that.  You have no idea the time spent just trying to connect two computers, or even just load a program you did not want to type in again.  And the error-correction was practically non-existent, so many times you just gave up and typed in pages and pages of code for the millionth time.  But It was super cool, you have no idea.  We were doing things nobody did.  I got sidetracked into fixing them, rather than programming them.  Probably should have started paypal, but whoops...

**Comment by peterahunt** [comment]
And technically, the computer speaker was for recording it, on a tape deck, the phone was when we wanted to send things, It was way way slower than the modems you probably used as a kid, if you did. Like 300 baud was a super upgrade from 72 baud.

Anyways...

**Comment by peterahunt** [comment]
We did all sorts of creative things, we were not using a modem, the 300 bps modem in the school was off limits.  You can move info on a tape if you try.  I recall the phone method not working particularly well, but it did work.  If you really want an example of what were were doing, read this page, its only a few minutes long...  Remember, there was simply not another way to move data between computers, networks did not exist as they exist today, and certainly not in our school.  USB sticks were not even on the horizon, and not all the computers had a floppy drive.  Just a keyboard, and analog sound, so we used sound.

https://arstechnica.com/staff/2018/11/first-encounter-compute-magazine-and-its-glorious-tedious-type-in-code/

Was pretty cool in the day.
