### ISSUE TITLE
I got "kex_exchange_identification: read: Connection reset"

### ISSUE THREAD

**Issue by hazardemircan** [quackduck/devzat#219]
Can someone explain why i am getting this?
Also i attempted to establish a telnet connection to devzat.hackclub.com on port 443, but the connection was unsuccessful.
![image](https://github.com/user-attachments/assets/88fac72f-be57-469d-bb3e-c6500b77b8eb)

**Comment by quackduck** [comment]
server was down. all good now

**Comment by hazardemircan** [comment]
@quackduck down on my first try, my luck lol

**Comment by quackduck** [comment]
my bad lol server was down for quite a while actually
