### ISSUE TITLE
How to delete a room

### ISSUE THREAD

**Issue by gansheer** [quackduck/devzat#224]
Is there a command that allows to delete a room (we tried rm #room-name and other equivalent without any success) ?

**Comment by quackduck** [comment]
that wouldn't be too hard to add to clean up extra rooms. i'd probably want it to be admin-use only. thoughts @Arkaeriit?

**Comment by gansheer** [comment]
Naively I through the `rm` command would do something since it displays some help text, but with this code there is no chance :smile:  :
https://github.com/quackduck/devzat/blob/3d2d7441185c356883c11f6207ef5c76e0d7c6b8/commands.go#L684-L691

And having the feature only for admin would be ideal IMHO.

**Comment by Arkaeriit** [comment]
> that wouldn't be too hard to add to clean up extra rooms. i'd probably want it to be admin-use only. thoughts @Arkaeriit?

An command to delete empty room would be a good idea. I don't think it would need need admin access as deleting empty rooms is harmless.

**Comment by Arkaeriit** [comment]
Should that command be `rm` or `rmdir` ?

**Comment by gansheer** [comment]
> A command to delete empty room would be a good idea. I don't think it would need need admin access as deleting empty rooms is harmless.

Out of curiousity, what is constitute a room as empty ? A room without any users using it at the time of the deletion ?

**Comment by quackduck** [comment]
Yes, can't see what else it could be tbh

**Comment by Arkaeriit** [comment]
We can probably close this now that #226 has been merged.
