### ISSUE TITLE
Abnormal exit prevents users from logging out

### ISSUE THREAD

**Issue by xnz233** [quackduck/devzat#228]
Thank you to the author for developing such interesting software！

 Perhaps it was due to my improper operation, I found that when I accidentally disconnected the Internet, my user was not logged off. Therefore, when I connect next time, it prompts me that my nickname is already used, so I must change my nickname.
![Screenshot_20240805_180138](https://github.com/user-attachments/assets/d8753c5f-3891-42c7-b48e-b8cf96b121e2)

 I have tried multiple times and it has always been like this.This problem should be easy to reproduce.

**Comment by Skydrgon** [comment]
Sometimes when I enter a command, he gets stuck and prevents me from exiting with the exit command, which I encounter when I force close the ssh client and reopen it.
It's going to be quite a while before he lets me log back in using that nickname. It was able to retain the colour I had configured, I'm not sure if it's the same id.
I can't use the nick command to change my nickname back to what I want until the old "me" is erased.

I've described the phenomenon I've encountered, and hope it's of some help!

**Comment by Arkaeriit** [comment]
@xnz233  This isn't a Devzat issue, this is a SSH client issue. If you SSH to a normal computer and have an internet issue, you will be stuck in a similar fashion.

@Skydrgon If you connect to Devzat with a flaky internet connection, you will get stuck and won't be able to properly logout. To fix your nickname issue, you can use the command `kick <your nickname>` to kick your old self out and be able to take back your nickname.

**Comment by xnz233** [comment]
@Arkaeriit Thank you for your response.  in fact, The problem I meet is same to Skydrgon .I will close this issue.

**Comment by Skydrgon** [comment]
Thank you for your replies!
