### ISSUE TITLE
will this project support server connect each other

### ISSUE THREAD

**Issue by EnderAvaritia** [quackduck/devzat#229]
will the devzat server support connect each other to expend the server

**Comment by Arkaeriit** [comment]
I feel like this would be very suitable for a plugin. I will start working on it.

**Comment by quackduck** [comment]
interesting

**Comment by Arkaeriit** [comment]
Development started here: https://github.com/Arkaeriit/devzat-courier

**Comment by EnderAvaritia** [comment]
> I feel like this would be very suitable for a plugin. I will start working on it.

thanks a lot

**Comment by Arkaeriit** [comment]
The plugin is now in a working order.

**Comment by quackduck** [comment]
absolutely incredible 👏
