### ISSUE TITLE
Translation support for README.md?

### ISSUE THREAD

**Issue by Skydrgon** [quackduck/devzat#235]
Hello developers, I would like to ask you if you need a Chinese translation of readme.md, I see that there are a lot of users from China and it might be helpful to have a translation of the local documentation.
My preconceived idea is to write a new document with the same layout as your readme.md document and name it readme-CN.md, I wonder if that makes sense?
Thank you for your time.

**Comment by quackduck** [comment]
that would be awesome. the english readme does need to be updated because it's sort of cringe rn

**Comment by Skydrgon** [comment]
I've finished updating locally, can I get a collaborator location to upload and pull requests?

**Comment by quackduck** [comment]
You can make a pull request without needing any special permissions

**Comment by Skydrgon** [comment]
Requests have been merged, thank you all!
