### ISSUE TITLE
How to view history|如何查看历史记录

### ISSUE THREAD

**Issue by specked2527** [quackduck/devzat#237]
Is this a hidden command? I can't find any command to view history until I see someone else use it.
```
: man extract
devbot: Usage: extract duration
        Extract the messages posted in  duration
```
use
: extract 24h

**Comment by quackduck** [comment]
It's from a plugin made by @Arkaeriit

**Comment by Arkaeriit** [comment]
Yep it's from this [plugin](https://github.com/Arkaeriit/devzat-extractor).
You can see the list of commands handled by plugins with the `plugin` command.
