### ISSUE TITLE
Markdown's image sending may cause the server to run blocked.

### ISSUE THREAD

**Issue by Skydrgon** [quackduck/devzat#241]
When assisting one of the users with Markdown commands, we encountered this issue. I reviewed the actual image and deemed it not particularly large, so I attempted to send the information and display the actual effect using text. However, immediately after, everyone experienced lag and was unable to send additional messages.
[https://images2.imgbox.com/8a/ca/CAU05KST_o.jpg](url) 
Here's the link to the image, not sure if this problem will resurface again. Previously, a similar phenomenon occurred when someone used images for spamming, and I believe this issue is not solely due to the user's network problems.

I'll provide screenshots from that time if needed. Thank you for your time.

**Comment by quackduck** [comment]
restarted the server just now, not sure what the problem is

**Comment by Skydrgon** [comment]
*knock knock

After a round of stress testing, how was it, did you see any difference?

**Comment by Skydrgon** [comment]
Marked it as completed and presumed to be an unknown network issue.
