### ISSUE TITLE
How to deploy to own server

### ISSUE THREAD

**Issue by shmilysy** [quackduck/devzat#25]
Can you write down the steps?

**Comment by shmilysy** [comment]
root@18a8b6f5022e:~/devzat-0.1.5# go build
go: downloading github.com/MichaelMure/go-term-markdown v0.1.4
go: downloading github.com/acarl005/stripansi v0.0.0-20180116102854-5a71ef0e047d
go: downloading github.com/fatih/color v1.10.0
go: downloading github.com/gliderlabs/ssh v0.3.2
go: downloading github.com/shurcooL/tictactoe v0.0.0-20190901224142-67fd35c6a520
go: downloading github.com/slack-go/slack v0.8.2
go: downloading golang.org/x/term v0.0.0-20210317153231-de623e64d2a6
go: downloading github.com/mattn/go-colorable v0.1.8
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading github.com/anmitsu/go-shlex v0.0.0-20200514113438-38f4b401e2be
go: downloading golang.org/x/crypto v0.0.0-20210322153248-0c34fe9e7dc2
go: downloading github.com/MichaelMure/go-term-text v0.3.1
go: downloading github.com/alecthomas/chroma v0.7.1
go: downloading github.com/eliukblau/pixterm/pkg/ansimage v0.0.0-20191210081756-9fb6cf8c2f75
go: downloading github.com/gomarkdown/markdown v0.0.0-20191123064959-2c17d62f5098
go: downloading github.com/kyokomi/emoji/v2 v2.2.8
go: downloading golang.org/x/net v0.0.0-20210226172049-e18ecbb05110
go: downloading github.com/gorilla/websocket v1.4.2
go: downloading github.com/pkg/errors v0.9.1
go: downloading golang.org/x/sys v0.0.0-20210402192133-700132347e07
go: downloading github.com/mattn/go-runewidth v0.0.12
go: downloading github.com/dlclark/regexp2 v1.1.6
go: downloading github.com/disintegration/imaging v1.6.2
go: downloading github.com/lucasb-eyer/go-colorful v1.0.3
go: downloading golang.org/x/image v0.0.0-20191206065243-da761ea9ff43
go: downloading github.com/rivo/uniseg v0.1.0
go: downloading github.com/danwakefield/fnmatch v0.0.0-20160403171240-cbb64ac3d964
**devchat.go:37:13: pattern slackAPI.txt: no matching files found**
root@18a8b6f5022e:~/devzat-0.1.5#

**Comment by quackduck** [comment]
No problemo, you just need a few empty files.

Run:
```shell
touch slackAPI.txt # supposed to contain the bot token (xoxb one) if you have a slack workspace
echo "{}" > twitter-creds.json # supposed to contain twitter credentials if you want to make a bot like @devzat on Twitter
```

You'll need to make sure you have ssh keys generated. Check if the file `~/.ssh/id_rsa.pub` is present. If it is, skip this step:
```shell
ssh-keygen # hit enter at each prompt it gives you
```

Now to start up the server just build and run! By default it runs on port 22 but you can change the port like this:
```shell
PORT=2222 ./devzat
```

Let me know of any other problems you have while trying to run your own server!

**Comment by quackduck** [comment]
Also, looking at the error messages it is clear that you aren't using the latest source code, you should download the latest [devchat.go](https://github.com/quackduck/devzat/blob/main/devchat.go)

**Comment by shmilysy** [comment]
wow! thank you~

**Comment by quackduck** [comment]
Sorry for replying so late lol, lemme know how it goes :)

**Comment by quackduck** [comment]
Also you might wanna change up the stuff in /people
And if you want to make your server a proper on you'll prolly need to remove the twitter and slack parts of the code completely.

**Comment by shmilysy** [comment]
Yes, I seem to have found this problem. Where is the specific path?~_~

**Comment by quackduck** [comment]
What problem did you find?

**Comment by shmilysy** [comment]
remove the twitter and slack parts of the code completely.
Where is the code

**Comment by shmilysy** [comment]
"devbot: err: twitter: 215 Bad Authentication data."

**Comment by quackduck** [comment]
yeah I mean that error won't harm you

**Comment by quackduck** [comment]
It'll be hard to completely remove all of it so just comment out this line: https://github.com/quackduck/devzat/blob/main/devchat.go#L251

Also, make sure you update to the latest source.

**Comment by shmilysy** [comment]
Perfect solution, this is a very interesting project, thank you for your contribution!

**Comment by quackduck** [comment]
Thanks for interacting with me! Also, make sure to drop Devzat a star if you haven't already lolol

**Comment by shmilysy** [comment]
It's already star! ovo

**Comment by quackduck** [comment]
❤️ 

Tell your friends about Devzat!
