### ISSUE TITLE
Add a way for users to 'protect' their name / nick

### ISSUE THREAD

**Issue by TheGreyDiamond** [quackduck/devzat#35]
It would be cool if you would be able to protect your username with a password or something so the other side can be sure that you are actually you. Just an idea.

**Comment by quackduck** [comment]
I think it's more free-ing if people don't have reserved usernames. Plus then I have to store less user data, yk?
Also, we already have an identification system, try running `./id <user>` the next time you're online!

**Comment by TheGreyDiamond** [comment]
Yeah problem is IPs in germany change every 24h. So the hash changes often.

**Comment by TheGreyDiamond** [comment]
How this could be fixed.

**Comment by quackduck** [comment]
No idea lol, discord also uses IP bans, so if it works for them it works for us

Alternatively we could add a new command that shows your pubkey fingerprint for identification (not for bans tho)

**Comment by TheGreyDiamond** [comment]
Yeah just because others do it doesn't mean it's good. This for example makes it almost impossible for german people to make themselves admin. At least most of them.

**Comment by quackduck** [comment]
admin on discord or devzat?

**Comment by TheGreyDiamond** [comment]
Devzat. Discord does not handle permissions via IP hashes.
