### ISSUE TITLE
MOTD

### ISSUE THREAD

**Issue by TAG-Epic** [quackduck/devzat#36]
A Message being sent to you when connecting which gives basic info would be pretty cool. Should probably be able to be changed by command aswell.

**Comment by quackduck** [comment]
sure, I'll add it to the joining message (rn, we show a help message the first time a user joins but this is based on IDs, which apparently are not quite reliable due to carrier grade NAT)

**Comment by quackduck** [comment]
nvm, it seems it wasn't working not because of NAT but because of a small programming fault I made
