### ISSUE TITLE
[BETA] Nick command

### ISSUE THREAD

**Issue by TAG-Epic** [quackduck/devzat#38]
There's no Nick command on beta

**Comment by Teraskull** [comment]
Temporary workaround, add your preferred nick into the ssh config:
```ssh-config
Host chat
  HostName devzat.hackclub.com
  User <your nick here>
```

**Comment by TAG-Epic** [comment]
Yup or username@chat

**Comment by quackduck** [comment]
Which beta

**Comment by quackduck** [comment]
epic you should open issues with your fork on your fork
