### ISSUE TITLE
Unban request

### ISSUE THREAD

**Issue by TheGreyDiamond** [quackduck/devzat#41]
Its a mobile data ip so, probably banning more then 1 person, also my enter button broke and pressed constatly. No text was typed. I was bannend, Please unban
[ID cfbbc1395ac6f6c1b7628ff814d158d1f1045ede7b85d7809e85015db8c0c270]

**Comment by quackduck** [comment]
Damn, getting yourself auto-banned is actually really hard lol, I’ll unban you dw

**Comment by TheGreyDiamond** [comment]
Thanks!

**Comment by quackduck** [comment]
Done!
