### ISSUE TITLE
Can't connect to the chat

### ISSUE THREAD

**Issue by ColeDrain** [quackduck/devzat#46]
I tried running the ssh devzat.hackclub.com command.

I keep getting this error: 

ssh: Connection to @devzat.hackclub.com:22 exited: Connect failed: Connection refused

**Comment by quackduck** [comment]
Fixed!

**Comment by ColeDrain** [comment]
That's cool, you're amazing bro.

**Comment by quackduck** [comment]
Thanks for letting me know lol
