### ISSUE TITLE
Ishan, what's going on with the server?

### ISSUE THREAD

**Issue by ColeDrain** [quackduck/devzat#51]

**Comment by quackduck** [comment]
I've been on a trip with low connectivity, server's not doing great

**Comment by ColeDrain** [comment]
Ah, should have guessed. Hope you're having a great time?
Are you on twitter? Maybe another way we can reach each other.

**Comment by quackduck** [comment]
I'm doing great, thanks! I am on Twitter: https://twitter.com/0xIshan
You can always email me at igoel.mail@gmail.com too
