### ISSUE TITLE
Unable to login without public key

### ISSUE THREAD

**Issue by Arkaeriit** [quackduck/devzat#59]
If we did not upload a public key to the server, it is impossible to log in.
If we upload a key with ssh-copy-id it works but I really think we should let people join without keys.

**Comment by Arkaeriit** [comment]
An option could be to let the port 22 open without any key needed and enable the key auth on the port 443.

**Comment by Arkaeriit** [comment]
The issue is still there. If you boot up a new machine or make a fresh virtual machine and run `ssh devzat.hackclub.com` you wikk get the error message `psedo@devzat.hackclub.com: Permission denied (publickey).`.
i think this is pretty bad and some people that used to log on devzat stopped because they could not login. As there is no feature using pubkey yet, the pubkey login should simply be simply be disabled.

**Comment by Arkaeriit** [comment]
Furthermore, even if we would like ta have the pubkey auth somehow, it is a bit broken in the ssh go server we are using.
When registering a new key with `ssh-copy-id`, a ghost user with our username stays logged in, preventing us from logging back.

**Comment by quackduck** [comment]
You don’t need ssh-copy-id! Simply generating keys and logging in normally works. The key is currently used for the id command.

**Comment by quackduck** [comment]
Awesome, merged
