### ISSUE TITLE
Devzat being down from time to time

### ISSUE THREAD

**Issue by Arkaeriit** [quackduck/devzat#63]
As you know, Devzat is down from time to time. I think I managed to witness it crash when I tried to log in. Here is a copy-paste of my terminal when trying to log in.
```
^[n.n]^ ~ >ssh devzat
                                                                            1h17m earlier
dunne: id dunne
2edd3297a02dd08d598fd0d8464de431e20cce345591fa73a89e3eabd5a786a1
dunne: users
[Arkaeriit dunne] 
dunne: id Arkaeriit 
d6acd2f5c5a8ef95563883032ef0b7c0239129b2d3672f964e5711b5016e05f5
dunne: kick d6acd2f5c5a8ef95563883032ef0b7c0239129b2d3672f964e5711b5016e05f5
User not found
dunne: kick Arkaeriit 
devbot: Not authorized
dunne: :(
devbot: dunne has left the chat
devbot: dunne stayed on for 2m
                                                                            1h16m earlier
devbot: https://twitter.com/devzat/status/1465281827774607369
                                                                            5m earlier
devbot: Arkaeriit has left the chat 
devbot: Arkaeriit stayed on for 3h0m 
Connection to devzat.hackclub.com closed by remote host.
Connection to devzat.hackclub.com closed.
^[n.n]^ ~ >ssh devzat
ssh: connect to host devzat.hackclub.com port 22: Connection refused
```
This happen at around 12:44 UTC.

A few minutes before the crash, I was disconnected because I turned down my computer and the crash happen when I tried to log back in. Maybe the crash is related to the unconventional exit.

**Comment by Arkaeriit** [comment]
I tried to replicate it locally but I couldn't. Could it be related to the way you start your server?

**Comment by quackduck** [comment]
I've been starting it the same way for a long time

**Comment by Arkaeriit** [comment]
I did not noticed any in about a week. Maybe PR #65 fixed the issue.
If there is no more issues this week, we could close the issue.

**Comment by quackduck** [comment]
let's close this for now; we'll open if we spot another instance
