### ISSUE TITLE
Unban request

### ISSUE THREAD

**Issue by adewinter** [quackduck/devzat#75]
Hi there,

I tried to join for the first time tonight and was kicked then kb'd immediately.  I'm guessing it has something to do with [your current spam issues](https://news.ycombinator.com/item?id=30694942) and me joining at a really bad time.   This is the message I see when I try to connect:
```
devbot: You are banned. If you feel this was a mistake, please reach out at github.com/quackduck/devzat/issues or email
        igoel.mail@gmail.com. Please include the following information: [ID
        42ae49dc6cdbb80b81ba2144385996e1b10cbb33896a062efbb68f9fe6cb1578]
```

Thanks for taking a look!

**Comment by quackduck** [comment]
You should be good now!

**Comment by adewinter** [comment]
Hmm, looks like I still can't join:
```
devbot: You are banned. If you feel this was a mistake, please reach out at github.com/quackduck/devzat/issues or email
        igoel.mail@gmail.com. Please include the following information: [ID
        42ae49dc6cdbb80b81ba2144385996e1b10cbb33896a062efbb68f9fe6cb1578]
```

I wonder if it might be my IP? I could also regen my ssh-key if that would help.

**Comment by quackduck** [comment]
That is super weird. Are you joining the same way you were before? If you're okay with sending me your public IP, you can email me with it (that would definitely get you unbanned)

**Comment by adewinter** [comment]
Ok will do

**Comment by quackduck** [comment]
Fixed 👍

**Comment by adewinter** [comment]
Woo thanks! Successfully connected 😁

**Comment by quackduck** [comment]
Great!
