### ISSUE TITLE
trivia bot question database

### ISSUE THREAD

**Issue by electronoob** [quackduck/devzat#80]
back when i ran a chat network we had a trivia bot, somewhere along the lines a questions database appeared and this is a snapshot of that. 

https://github.com/electronoob/Voyager/blob/master/Modules/Trivia/questions.txt

pretty simple format. seems like the kind of thing you might want to add to your server.

`France declares war on Austria, Prussia and Sardinia in which year*1792`

**Comment by polyrain** [comment]
Putting forward this for where to source questions from, just need to query their API and should be an infinite amount of questions: https://opentdb.com/api_config.php

**Comment by polyrain** [comment]
> that's cool @polyrain
> i will say though that the database i linked has 49,743 entries, and that api has about 4,000.

right, but it's much easier to query an API than deal with managing it ourselves :)

**Comment by Arkaeriit** [comment]
Should we close this as the trivia bot is alive and well?
