### ISSUE TITLE
Unicode support

### ISSUE THREAD

**Issue by runvnc** [quackduck/devzat#82]
Unicode support would be nice.

**Comment by quackduck** [comment]
Unicode support did exist, randomly broke sometime recently, possibly because of me adding keyboard shortcuts to my fork of x/term

**Comment by runvnc** [comment]
This https://github.com/quackduck/term/commit/a4fd7c43aa8153325c0dd89c3d55fe987c2c25c4 ?

**Comment by quackduck** [comment]
Maybe, I’m not sure

**Comment by quackduck** [comment]
Yep, that broke it: https://go.dev/play/p/KumYER306MG

**Comment by quackduck** [comment]
Sorry it took so long, it's fixed now
