### ISSUE TITLE
Preference persistence

### ISSUE THREAD

**Issue by Narnillian** [quackduck/devzat#87]
For example, once I have joined the chat, I would run `settings ~/.ssh/devzat_settings`. It would look something like this:
```
color pastel green
nick narnillian
pronouns he/him
```
Essentially, it would hold some boilerplate commands, with the same syntax and execution as if I ran them manually. Any command could be run from this file

**Comment by quackduck** [comment]
The ssh server can’t access your local file system, but this can be done by storing preferences on the server

**Comment by CodeLongAndProsper90** [comment]
Btw I'm working on this, haven't made a PR yet, though

**Comment by quackduck** [comment]
This issue will be fixed by #91
