### ISSUE TITLE
Proposal for adding an option to cancel the name changing process

### ISSUE THREAD

**Issue by Spico197** [quackduck/devzat#88]
I tried to change my name by using `nick` command. However, when I entered the name changing prompt, I found I cannot cancel the operation and I had to type another name except the current one (if you type the current name, it will warn you the name is already in use).
I think there should be an option to support cancel such operations, or stay things unchanged. Just for a reference, my personal habit is to use `Ctrl+D` to stop input in linux systems. But here I will exit the chat room directly if I type `Ctrl+D`.

Relevant codes are in below:
https://github.com/quackduck/devzat/blob/b836179bd0584b1112dc3b011668d433cdfa9768/devchat.go#L384

**Comment by quackduck** [comment]
Alright 👍
